-- 코드를 입력하세요
WITH A AS(
    SELECT AUTHOR_ID, CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
    FROM BOOK_SALES AS BS
    JOIN (
        SELECT BOOK_ID, CATEGORY, AUTHOR_ID, PRICE
        FROM BOOK) AS B USING(BOOK_ID)
    WHERE SALES_DATE LIKE '2022-01%'
    GROUP BY AUTHOR_ID, CATEGORY
)

SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, TOTAL_SALES
FROM A
JOIN AUTHOR USING(AUTHOR_ID)
ORDER BY AUTHOR_ID, CATEGORY DESC;