WITH HOLY AS (
    SELECT PARENT_ID AS ID, COUNT(PARENT_ID) AS CHILD_COUNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
)

SELECT 
    ID,
    CASE WHEN CHILD_COUNT IS NULL THEN 0 ELSE CHILD_COUNT END AS CHILD_COUNT
FROM HOLY
RIGHT JOIN ECOLI_DATA
    USING(ID);