-- 코드를 입력하세요
SELECT FOOD_TYPE, 
        REST_ID, 
        REST_NAME, 
        FAVORITES
FROM(
    SELECT 
        FOOD_TYPE, 
        REST_ID, 
        REST_NAME, 
        FAVORITES, 
        MAX(FAVORITES) OVER(PARTITION BY FOOD_TYPE) AS MAX_FAVORITES
    FROM REST_INFO
    ORDER BY FOOD_TYPE
) AS MAX_FAV
WHERE FAVORITES = MAX_FAVORITES
ORDER BY FOOD_TYPE DESC;

WITH MF AS(
    SELECT 
        FOOD_TYPE, 
        REST_ID, 
        REST_NAME, 
        FAVORITES, 
        MAX(FAVORITES) OVER(PARTITION BY FOOD_TYPE) AS MAX_FAVORITES
    FROM REST_INFO
    ORDER BY FOOD_TYPE
)

SELECT
    FOOD_TYPE, 
    REST_ID, 
    REST_NAME, 
    FAVORITES
FROM MF
WHERE FAVORITES = MAX_FAVORITES
ORDER BY FOOD_TYPE DESC;

WITH MF AS(
    SELECT 
        FOOD_TYPE, 
        REST_ID, 
        REST_NAME, 
        FAVORITES, 
        ROW_NUMBER() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS MAX_FAVORITES
    FROM REST_INFO
    ORDER BY FOOD_TYPE
)

SELECT
    FOOD_TYPE, 
    REST_ID, 
    REST_NAME, 
    FAVORITES
FROM MF
WHERE MAX_FAVORITES = 1
ORDER BY FOOD_TYPE DESC;