-- 코드를 입력하세요
WITH IN_NO AS(
    SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE NOT LIKE 'SPAYED%' AND SEX_UPON_INTAKE NOT LIKE 'NEUTERED%'
),
OUT_YES AS(
    SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
    FROM ANIMAL_OUTS
    WHERE SEX_UPON_OUTCOME  LIKE 'SPAYED%' OR SEX_UPON_OUTCOME LIKE 'NEUTERED%'
)

SELECT IN_NO.ANIMAL_ID, IN_NO.ANIMAL_TYPE, IN_NO.NAME
FROM IN_NO
JOIN OUT_YES USING(ANIMAL_ID)
ORDER BY ANIMAL_ID;