-- 코드를 입력하세요
WITH PERIOD AS(
    SELECT CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS PERIOD
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT CAR_ID, ROUND(AVG(PERIOD), 1) AS AVERAGE_DURATION
FROM PERIOD
GROUP BY CAR_ID
HAVING AVG(PERIOD) >= 7
ORDER BY ROUND(AVG(PERIOD), 1) DESC, CAR_ID DESC;