-- 코드를 작성해주세요
SELECT 
    QUARTER,
    COUNT(ID) AS ECOLI_COUNT
FROM(
    SELECT 
        *,
        CONCAT(QUARTER(DIFFERENTIATION_DATE), 'Q') AS QUARTER    
    FROM ECOLI_DATA
) Q
GROUP BY QUARTER
ORDER BY QUARTER;