-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, PT_NO, APP.MCDP_CD, DR_NAME, APNT_YMD
FROM (
    SELECT APNT_NO, PT_NO, MCDP_CD, MDDR_ID, APNT_YMD
    FROM APPOINTMENT
    WHERE DATE(APNT_YMD) = '2022-04-13' AND MCDP_CD = 'CS' AND APNT_CNCL_YN = 'N'
) APP
JOIN PATIENT PAT USING(PT_NO)
JOIN DOCTOR DOC ON APP.MDDR_ID = DOC.DR_ID
ORDER BY APNT_YMD;