-- 코드를 입력하세요
WITH OVER_5 AS(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE(START_DATE) >= '2022-08-01' AND DATE(START_DATE) < '2022-11-01'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE(START_DATE) >= '2022-08-01' AND DATE(START_DATE) < '2022-11-01'
    AND CAR_ID IN(SELECT CAR_ID FROM OVER_5)
GROUP BY MONTH(START_DATE), CAR_ID
HAVING COUNT(*) IS NOT NULL
ORDER BY MONTH, CAR_ID DESC;