SELECT 
    SCORE,
    EMP_NO,
    EMP_NAME, 
    POSITION,
    EMAIL
FROM (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
    ORDER BY SUM(SCORE) DESC
    LIMIT 1
) BS
JOIN HR_EMPLOYEES USING(EMP_NO)
JOIN HR_DEPARTMENT USING(DEPT_ID);